package fhir

func ResourceTypeToIResource(resourceType ResourceType) IResource {
	switch resourceType {
	case ResourceTypeAccount:
		return &Account{}
	case ResourceTypeActivityDefinition:
		return &ActivityDefinition{}
	case ResourceTypeAdverseEvent:
		return &AdverseEvent{}
	case ResourceTypeAllergyIntolerance:
		return &AllergyIntolerance{}
	case ResourceTypeAppointment:
		return &Appointment{}
	case ResourceTypeAppointmentResponse:
		return &AppointmentResponse{}
	case ResourceTypeAuditEvent:
		return &AuditEvent{}
	case ResourceTypeBasic:
		return &Basic{}
	case ResourceTypeBinary:
		return &Binary{}
	case ResourceTypeBodySite:
		return &BodySite{}
	case ResourceTypeBundle:
		return &Bundle{}
	case ResourceTypeCapabilityStatement:
		return &CapabilityStatement{}
	case ResourceTypeCarePlan:
		return &CarePlan{}
	case ResourceTypeCareTeam:
		return &CareTeam{}
	case ResourceTypeChargeItem:
		return &ChargeItem{}
	case ResourceTypeClaim:
		return &Claim{}
	case ResourceTypeClaimResponse:
		return &ClaimResponse{}
	case ResourceTypeClinicalImpression:
		return &ClinicalImpression{}
	case ResourceTypeCodeSystem:
		return &CodeSystem{}
	case ResourceTypeCommunication:
		return &Communication{}
	case ResourceTypeCommunicationRequest:
		return &CommunicationRequest{}
	case ResourceTypeCompartmentDefinition:
		return &CompartmentDefinition{}
	case ResourceTypeComposition:
		return &Composition{}
	case ResourceTypeConceptMap:
		return &ConceptMap{}
	case ResourceTypeCondition:
		return &Condition{}
	case ResourceTypeConsent:
		return &Consent{}
	case ResourceTypeContract:
		return &Contract{}
	case ResourceTypeCoverage:
		return &Coverage{}
	case ResourceTypeDataElement:
		return &DataElement{}
	case ResourceTypeDetectedIssue:
		return &DetectedIssue{}
	case ResourceTypeDevice:
		return &Device{}
	case ResourceTypeDeviceComponent:
		return &DeviceComponent{}
	case ResourceTypeDeviceMetric:
		return &DeviceMetric{}
	case ResourceTypeDeviceRequest:
		return &DeviceRequest{}
	case ResourceTypeDeviceUseStatement:
		return &DeviceUseStatement{}
	case ResourceTypeDiagnosticReport:
		return &DiagnosticReport{}
	case ResourceTypeDocumentManifest:
		return &DocumentManifest{}
	case ResourceTypeDocumentReference:
		return &DocumentReference{}
	case ResourceTypeDomainResource:
		return &DomainResource{}
	case ResourceTypeEligibilityRequest:
		return &EligibilityRequest{}
	case ResourceTypeEligibilityResponse:
		return &EligibilityResponse{}
	case ResourceTypeEncounter:
		return &Encounter{}
	case ResourceTypeEndpoint:
		return &Endpoint{}
	case ResourceTypeEnrollmentRequest:
		return &EnrollmentRequest{}
	case ResourceTypeEnrollmentResponse:
		return &EnrollmentResponse{}
	case ResourceTypeEpisodeOfCare:
		return &EpisodeOfCare{}
	case ResourceTypeExpansionProfile:
		return &ExpansionProfile{}
	case ResourceTypeExplanationOfBenefit:
		return &ExplanationOfBenefit{}
	case ResourceTypeFamilyMemberHistory:
		return &FamilyMemberHistory{}
	case ResourceTypeFlag:
		return &Flag{}
	case ResourceTypeGoal:
		return &Goal{}
	case ResourceTypeGraphDefinition:
		return &GraphDefinition{}
	case ResourceTypeGroup:
		return &Group{}
	case ResourceTypeGuidanceResponse:
		return &GuidanceResponse{}
	case ResourceTypeHealthcareService:
		return &HealthcareService{}
	case ResourceTypeImagingManifest:
		return &ImagingManifest{}
	case ResourceTypeImagingStudy:
		return &ImagingStudy{}
	case ResourceTypeImmunization:
		return &Immunization{}
	case ResourceTypeImmunizationRecommendation:
		return &ImmunizationRecommendation{}
	case ResourceTypeImplementationGuide:
		return &ImplementationGuide{}
	case ResourceTypeLibrary:
		return &Library{}
	case ResourceTypeLinkage:
		return &Linkage{}
	case ResourceTypeList:
		return &List{}
	case ResourceTypeLocation:
		return &Location{}
	case ResourceTypeMeasure:
		return &Measure{}
	case ResourceTypeMeasureReport:
		return &MeasureReport{}
	case ResourceTypeMedia:
		return &Media{}
	case ResourceTypeMedication:
		return &Medication{}
	case ResourceTypeMedicationAdministration:
		return &MedicationAdministration{}
	case ResourceTypeMedicationDispense:
		return &MedicationDispense{}
	case ResourceTypeMedicationRequest:
		return &MedicationRequest{}
	case ResourceTypeMedicationStatement:
		return &MedicationStatement{}
	case ResourceTypeMessageDefinition:
		return &MessageDefinition{}
	case ResourceTypeMessageHeader:
		return &MessageHeader{}
	case ResourceTypeNamingSystem:
		return &NamingSystem{}
	case ResourceTypeNutritionOrder:
		return &NutritionOrder{}
	case ResourceTypeObservation:
		return &Observation{}
	case ResourceTypeOperationDefinition:
		return &OperationDefinition{}
	case ResourceTypeOperationOutcome:
		return &OperationOutcome{}
	case ResourceTypeOrganization:
		return &Organization{}
	case ResourceTypeParameters:
		return &Parameters{}
	case ResourceTypePatient:
		return &Patient{}
	case ResourceTypePaymentNotice:
		return &PaymentNotice{}
	case ResourceTypePaymentReconciliation:
		return &PaymentReconciliation{}
	case ResourceTypePerson:
		return &Person{}
	case ResourceTypePlanDefinition:
		return &PlanDefinition{}
	case ResourceTypePractitioner:
		return &Practitioner{}
	case ResourceTypePractitionerRole:
		return &PractitionerRole{}
	case ResourceTypeProcedure:
		return &Procedure{}
	case ResourceTypeProcedureRequest:
		return &ProcedureRequest{}
	case ResourceTypeProcessRequest:
		return &ProcessRequest{}
	case ResourceTypeProcessResponse:
		return &ProcessResponse{}
	case ResourceTypeProvenance:
		return &Provenance{}
	case ResourceTypeQuestionnaire:
		return &Questionnaire{}
	case ResourceTypeQuestionnaireResponse:
		return &QuestionnaireResponse{}
	case ResourceTypeReferralRequest:
		return &ReferralRequest{}
	case ResourceTypeRelatedPerson:
		return &RelatedPerson{}
	case ResourceTypeRequestGroup:
		return &RequestGroup{}
	case ResourceTypeResearchStudy:
		return &ResearchStudy{}
	case ResourceTypeResearchSubject:
		return &ResearchSubject{}
	case ResourceTypeRiskAssessment:
		return &RiskAssessment{}
	case ResourceTypeSchedule:
		return &Schedule{}
	case ResourceTypeSearchParameter:
		return &SearchParameter{}
	case ResourceTypeSequence:
		return &Sequence{}
	case ResourceTypeServiceDefinition:
		return &ServiceDefinition{}
	case ResourceTypeSlot:
		return &Slot{}
	case ResourceTypeSpecimen:
		return &Specimen{}
	case ResourceTypeStructureDefinition:
		return &StructureDefinition{}
	case ResourceTypeStructureMap:
		return &StructureMap{}
	case ResourceTypeSubscription:
		return &Subscription{}
	case ResourceTypeSubstance:
		return &Substance{}
	case ResourceTypeSupplyDelivery:
		return &SupplyDelivery{}
	case ResourceTypeSupplyRequest:
		return &SupplyRequest{}
	case ResourceTypeTask:
		return &Task{}
	case ResourceTypeTestReport:
		return &TestReport{}
	case ResourceTypeTestScript:
		return &TestScript{}
	case ResourceTypeValueSet:
		return &ValueSet{}
	case ResourceTypeVisionPrescription:
		return &VisionPrescription{}
	default:
		return nil
	}
}
